In [1]:
from selenium import webdriver
import pandas as pd
import numpy as np
import time

In [2]:
driver = webdriver.Chrome('chromedriver.exe')

In [3]:
driver.get("http://info.nec.go.kr/main/showDocument.xhtml?electionId=0000000000&topMenuId=VC&secondMenuId=VCCP09")
time.sleep(1)

In [4]:
driver.find_element_by_id('electionType1').click()
time.sleep(1)

In [8]:
driver.find_element_by_xpath('//*[@id="electionName"]/option[@value='+str(20170509)+']').click()
time.sleep(1)

In [7]:
driver.find_element_by_xpath('//*[@id="electionCode"]/option[@value='+str(1)+']').click()
time.sleep(1)

In [24]:
driver.find_element_by_xpath('//*[@id="cityCode"]/option[@value='+str(0)+']').click()
time.sleep(1)

In [25]:
driver.find_element_by_id('searchBtn').click()
time.sleep(1)

In [26]:
table = driver.find_element_by_id('table01')
people = table.find_elements_by_class_name('alignC')

In [60]:
data= []
tb = driver.find_element_by_tag_name('tbody')
tr_lst = tb.find_elements_by_tag_name('tr')
for tr in tr_lst:
    td_lst = tr.find_elements_by_tag_name('td')
    temp = []
    for td in td_lst:
        temp.append(td.text.replace(',','').replace('\n',''))
    data.append(temp)

In [64]:
with open('elect.csv','w') as file:
    file.write('{},{},{},'.format(driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[1]/th[1]').text,
                                 driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[1]/th[2]').text,
                                driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[1]/th[3]').text))
    for f in people:
        file.write('{},'.format(f.text.replace('\n', ' ')))

    file.write('{},{},{}\n'.format(driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[2]/th[14]').text,
        driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[1]/th[5]').text.replace('\n',' '),
         driver.find_element_by_xpath('//*[@id="table01"]/thead/tr[1]/th[6]').text))
    for d in data:
        i=0
        for l in d:
            if (i != 0):
                file.write(',')
            file.write('{}'.format(l))
            i=1
        file.write('\n')

In [65]:
data

[['합계',
  '42479710',
  '32807908',
  '13423800(41.08)',
  '7852849(24.03)',
  '6998342(21.41)',
  '2208771(6.76)',
  '2017458(6.17)',
  '42949(0.13)',
  '6040(0.01)',
  '21709(0.06)',
  '9140(0.02)',
  '27229(0.08)',
  '11355(0.03)',
  '18543(0.05)',
  '33990(0.10)',
  '32672175',
  '135733',
  '9671802'],
 ['서울특별시',
  '8382999',
  '6590646',
  '2781345(42.34)',
  '1365285(20.78)',
  '1492767(22.72)',
  '476973(7.26)',
  '425459(6.47)',
  '9987(0.15)',
  '789(0.01)',
  '3554(0.05)',
  '1938(0.02)',
  '3416(0.05)',
  '1277(0.01)',
  '2177(0.03)',
  '3950(0.06)',
  '6568917',
  '21729',
  '1792353'],
 ['부산광역시',
  '2950224',
  '2261633',
  '872127(38.71)',
  '720484(31.98)',
  '378907(16.82)',
  '162480(7.21)',
  '109329(4.85)',
  '2651(0.11)',
  '276(0.01)',
  '1316(0.05)',
  '465(0.02)',
  '981(0.04)',
  '496(0.02)',
  '1041(0.04)',
  '2156(0.09)',
  '2252709',
  '8924',
  '688591'],
 ['대구광역시',
  '2043276',
  '1581347',
  '342620(21.76)',
  '714205(45.36)',
  '235757(14.97)',
  '198459(12.60)',
  '74440(4.72)',
  '4057(0.25)',
  '259(0.01)',
  '563(0.03)',
  '324(0.02)',
  '804(0.05)',
  '401(0.02)',
  '986(0.06)',
  '1501(0.09)',
  '1574376',
  '6971',
  '461929'],
 ['인천광역시',
  '2409031',
  '1820091',
  '747090(41.20)',
  '379191(20.91)',
  '428888(23.65)',
  '118691(6.54)',
  '129925(7.16)',
  '2646(0.14)',
  '374(0.02)',
  '1618(0.08)',
  '410(0.02)',
  '1230(0.06)',
  '594(0.03)',
  '625(0.03)',
  '1681(0.09)',
  '1812963',
  '7128',
  '588940'],
 ['광주광역시',
  '1166901',
  '957321',
  '583847(61.14)',
  '14882(1.55)',
  '287222(30.08)',
  '20862(2.18)',
  '43719(4.57)',
  '152(0.01)',
  '111(0.01)',
  '655(0.06)',
  '103(0.01)',
  '2265(0.23)',
  '136(0.01)',
  '264(0.02)',
  '614(0.06)',
  '954832',
  '2489',
  '209580'],
 ['대전광역시',
  '1220602',
  '945897',
  '404545(42.93)',
  '191376(20.30)',
  '218769(23.21)',
  '59820(6.34)',
  '63669(6.75)',
  '1069(0.11)',
  '168(0.01)',
  '620(0.06)',
  '234(0.02)',
  '611(0.06)',
  '256(0.02)',
  '406(0.04)',
  '758(0.08)',
  '942301',
  '3596',
  '274705'],
 ['울산광역시',
  '941093',
  '744960',
  '282794(38.14)',
  '203602(27.46)',
  '128520(17.33)',
  '60289(8.13)',
  '62187(8.38)',
  '829(0.11)',
  '128(0.01)',
  '575(0.07)',
  '240(0.03)',
  '641(0.08)',
  '220(0.02)',
  '411(0.05)',
  '926(0.12)',
  '741362',
  '3598',
  '196133'],
 ['세종특별자치시',
  '189421',
  '152801',
  '77767(51.08)',
  '23211(15.24)',
  '32010(21.02)',
  '9192(6.03)',
  '9353(6.14)',
  '153(0.10)',
  '34(0.02)',
  '88(0.05)',
  '42(0.02)',
  '126(0.08)',
  '50(0.03)',
  '76(0.04)',
  '135(0.08)',
  '152237',
  '564',
  '36620'],
 ['경기도',
  '10262309',
  '7916009',
  '3319812(42.08)',
  '1637345(20.75)',
  '1807308(22.91)',
  '540023(6.84)',
  '546373(6.92)',
  '10778(0.13)',
  '1302(0.01)',
  '5058(0.06)',
  '1858(0.02)',
  '6139(0.07)',
  '2213(0.02)',
  '2883(0.03)',
  '6553(0.08)',
  '7887645',
  '28364',
  '2346300'],
 ['강원도',
  '1287173',
  '955885',
  '324768(34.16)',
  '284909(29.97)',
  '206840(21.75)',
  '65278(6.86)',
  '62389(6.56)',
  '1426(0.15)',
  '252(0.02)',
  '787(0.08)',
  '321(0.03)',
  '876(0.09)',
  '570(0.05)',
  '870(0.09)',
  '1350(0.14)',
  '950636',
  '5249',
  '331288'],
 ['충청북도',
  '1303688',
  '975441',
  '374806(38.61)',
  '255502(26.32)',
  '211454(21.78)',
  '57282(5.90)',
  '65095(6.70)',
  '1153(0.11)',
  '308(0.03)',
  '722(0.07)',
  '421(0.04)',
  '840(0.08)',
  '686(0.07)',
  '943(0.09)',
  '1347(0.13)',
  '970559',
  '4882',
  '328247'],
 ['충청남도',
  '1711912',
  '1240204',
  '476661(38.62)',
  '306614(24.84)',
  '290216(23.51)',
  '68521(5.55)',
  '83868(6.79)',
  '1415(0.11)',
  '324(0.02)',
  '1148(0.09)',
  '429(0.03)',
  '1260(0.10)',
  '803(0.06)',
  '1025(0.08)',
  '1662(0.13)',
  '1233946',
  '6258',
  '471708'],
 ['전라북도',
  '1525626',
  '1205794',
  '778747(64.84)',
  '40231(3.34)',
  '285467(23.76)',
  '30802(2.56)',
  '59296(4.93)',
  '451(0.03)',
  '240(0.01)',
  '1080(0.08)',
  '345(0.02)',
  '1186(0.09)',
  '499(0.04)',
  '589(0.04)',
  '2070(0.17)',
  '1201003',
  '4791',
  '319832'],
 ['전라남도',
  '1572838',
  '1238738',
  '737921(59.87)',
  '30221(2.45)',
  '378179(30.68)',
  '25819(2.09)',
  '49509(4.01)',
  '454(0.03)',
  '272(0.02)',
  '1319(0.10)',
  '315(0.02)',
  '3817(0.30)',
  '839(0.06)',
  '782(0.06)',
  '2965(0.24)',
  '1232412',
  '6326',
  '334100'],
 ['경상북도',
  '2249984',
  '1711627',
  '369726(21.73)',
  '827237(48.62)',
  '253905(14.92)',
  '149017(8.75)',
  '88080(5.17)',
  '3053(0.17)',
  '476(0.02)',
  '1054(0.06)',
  '861(0.05)',
  '1308(0.07)',
  '1068(0.06)',
  '2942(0.17)',
  '2499(0.14)',
  '1701226',
  '10401',
  '538357'],
 ['경상남도',
  '2744633',
  '2135055',
  '779731(36.73)',
  '790491(37.24)',
  '284272(13.39)',
  '142479(6.71)',
  '113051(5.32)',
  '2290(0.10)',
  '458(0.02)',
  '1240(0.05)',
  '721(0.03)',
  '1394(0.06)',
  '1011(0.04)',
  '2234(0.10)',
  '3267(0.15)',
  '2122639',
  '12416',
  '609578'],
 ['제주특별자치도',
  '518000',
  '374459',
  '169493(45.51)',
  '68063(18.27)',
  '77861(20.90)',
  '22784(6.11)',
  '31716(8.51)',
  '385(0.10)',
  '269(0.07)',
  '312(0.08)',
  '113(0.03)',
  '335(0.08)',
  '236(0.06)',
  '289(0.07)',
  '556(0.14)',
  '372412',
  '2047',
  '143541']]